version: '3'
services:
  php:
    build: 
      context: './docker/php'
    volumes:
      - './src:/var/www/html'
   
  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - './src:/var/www/html'
      - './docker/nginx/conf.d:/etc/nginx/conf.d'
      - './docker/nginx/html:/usr/share/nginx/html'
   
  mysql:
    image: mysql:8
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - './mysql:/var/lib/mysql'
